@IsTest
public class MDM_Location_UpsertLocationTest {
    @istest
    Static void TestafterInsert_afterupdate()
    {
        
       /* MDM_Location_configuration__c mdc = new MDM_Location_configuration__c();
        mdc.name='MDM_IntegrationUser';
        mdc.Value__c = 'Ramakrishnan.Ramadur@crossmark.com.mdmlocuat' ;
        insert mdc;
        
        MDM_Location_configuration__c mdc1 = new MDM_Location_configuration__c();
        mdc1.name='DeleteStageRecordsBeforeInsert';
        mdc1.Value__c = 'true' ;
        insert mdc1;
        
        MDM_Source__c lsc = new MDM_Source__c();
        lsc.Name = 'SalesForce';
        insert(lsc);
        
        Master_Location_Country__C cnt = new Master_Location_Country__C();
        cnt.Name = 'TEST_COUNTRY';
        insert(cnt);
        
        Master_Location_State__C sta = new Master_Location_State__C();
        sta.Name = '--';
        sta.Country__c = cnt.id;
        insert(sta);
        
        Master_Location_Banner__c bnr= new Master_Location_Banner__c();
        bnr.Name = 'TEST_BANNER';
        insert(bnr);
        
        Master_Location_OwningCompany__c ocp = new Master_Location_OwningCompany__c();
        ocp.Name = 'TEST_OWNINGCOMPANY';
        insert(ocp);
        
        Master_Location_TradeChannel__c tch = new Master_Location_TradeChannel__c();
        tch.Name = 'TEST_TRADECHANNEL';
        insert(tch);
        
        Master_Location_Location__c oLocation = new Master_Location_Location__c();
        oLocation.name = 'TEST_NAME';
        oLocation.Address_1__c = 'TEST Home Address_1' ;
        oLocation.Address_2__c = 'TEST Home Address_2__c' ;
        oLocation.Address_3__c = 'TEST Home Address_3__c' ;
        oLocation.Banner__c   = bnr.id;
        oLocation.City__c     = 'TEST_City';
        oLocation.Country__c  = cnt.id;
        oLocation.Latitude__c     = 0.0;
        oLocation.Location_Number__c  = '1001';
        oLocation.Location_Type__c    = 'Business';
        oLocation.Longitude__c    = 0.0;
        oLocation.OwningCompany__c   = ocp.id;
        oLocation.Postal_Code__c  = '452369';
        oLocation.State__c    = sta.id; 
        oLocation.Store_Phone_Number__c   = '12345896'; 
        oLocation.TradeChannel__c     = tch.id;
        //oLocation.TradeSubChannel__c  = '';
        oLocation.LocationStatus__c  = 'OPEN';
        oLocation.DataOverrideFlag__c  = true; 
        oLocation.ValidateUpsert__c  = true; 
        Test.startTest();
        insert(oLocation);
        Test.stopTest();*/
    }
}